name: 'init-go'
description: 'Check out the repo and setup-go'
inputs:
  go-mod:
    description: 'Go mod file'
    required: false
  go-version:
    description: 'Go versions to use'
    required: false
runs:
  using: "composite"
  steps:
    - name: Checkout repo
      uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
      with:
        fetch-depth: 0

    - name: Setup Go
      uses: actions/setup-go@e75c3e80bcde46e322cd5845ae46582947c9becd
      with:
        go-version-file: ${{ inputs.go-mod }}
        cache-dependency-path: "**/go.sum"
        go-version: ${{ inputs.go-version }}
