name: 'init-go'
description: 'Check out the repo and setup-go'
inputs:
  go-mod:
    description: 'Go mod file'
    required: false
  version:
    description: 'Go versions to use'
    required: false
runs:
  using: "composite"
  steps:
    - name: Harden Runner
      uses: step-security/harden-runner@f4f3f445f343c08c93d7771433e8dee4267e05b9
      with:
        disable-sudo: true
        egress-policy: block
        allowed-endpoints: >
          api.github.com:443
          github.com:443
          golang.org:443
          objects.githubusercontent.com:443
          proxy.golang.org:443
          storage.googleapis.com:443
          sum.golang.org:443
          
    - name: Checkout repo
      uses: actions/checkout@b80ff79f1755d06ba70441c368a6fe801f5f3a62
      with:
        fetch-depth: 0

    - name: Setup Go
      uses: actions/setup-go@4ab57d7ea2fd0c9948210b2e0784e280674e7144
      with:
        go-version-file: ${{ inputs.go-mod }}
        go-version: ${{ inputs.go-version }}
