name: 'init-go'
description: 'Check out the repo and setup-go'
inputs:
  go-mod:
    description: 'Go mod file'
    required: false
  go-version:
    description: 'Go versions to use'
    required: false
runs:
  using: "composite"
  steps:
    - name: Harden Runner
      uses: step-security/harden-runner@8a09271fed8277ab7fb02dbb5917c8d0e78323b4
      with:
        disable-sudo: true
        egress-policy: block
        allowed-endpoints: >
          api.github.com:443
          github.com:443
          golang.org:443
          objects.githubusercontent.com:443
          proxy.golang.org:443
          storage.googleapis.com:443
          sum.golang.org:443
          
    - name: Checkout repo
      uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2
      with:
        fetch-depth: 0

    - name: Setup Go
      uses: actions/setup-go@c4c114188661c0fa735e5b938764519fc6e8efa9
      with:
        go-version-file: ${{ inputs.go-mod }}
        cache-dependency-path: "**/go.sum"
        go-version: ${{ inputs.go-version }}
