name: 'init-go'
description: 'Check out the repo and setup-go'
inputs:
  go-mod:
    description: 'Go mod file'
    required: false
    default: '**/go.mod'
  go-version:
    description: 'Go versions to use'
    required: false
runs:
  using: "composite"
  steps:
    - name: Checkout repo
      uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
      with:
        fetch-depth: 0

    - name: Prepare Go caches
      shell: bash
      run: mkdir -p "$HOME/.cache/go-build" "$HOME/go/pkg/mod"

    - name: Setup Go
      uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5
      with:
        go-version-file: ${{ inputs.go-mod }}
        cache-dependency-path: "**/go.sum"
        go-version: ${{ inputs.go-version }}
