#
# SPDX-License-Identifier: MIT
#
# Copyright (C) 2026 Daniel Bourdrez. All Rights Reserved.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree or at
# https://spdx.org/licenses/MIT.html
#

---

name: 'init-go'
description: 'Check out the repo and setup-go'
inputs:
  go-mod:
    description: 'Go mod file'
    required: false
  go-sum:
    description: 'Go mod file'
    required: false
    default: "**/go.sum"
  go-version:
    description: 'Go versions to use'
    required: false
runs:
  using: "composite"
  steps:
    - name: Checkout repo
      uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
      with:
        fetch-depth: 0

    - name: Prepare Go caches
      shell: bash
      run: mkdir -p "$HOME/.cache/go-build" "$HOME/go/pkg/mod"

    - name: Setup Go
      uses: actions/setup-go@a5f9b05d2d216f63e13859e0d847461041025775
      with:
        go-version-file: ${{ inputs.go-mod }}
        cache-dependency-path: ${{ inputs.go-sum }}
        go-version: ${{ inputs.go-version }}
