name: 'init-go'
description: 'Check out the repo and setup-go'
inputs:
  go-mod:
    description: 'Go mod file'
    required: false
  go-version:
    description: 'Go versions to use'
    required: false
runs:
  using: "composite"
  steps:
    - name: Checkout repo
      uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
      with:
        fetch-depth: 0

    - name: Prepare Go caches
      shell: bash
      run: mkdir -p "$HOME/.cache/go-build" "$HOME/go/pkg/mod"

    - name: Setup Go
      uses: actions/setup-go@faf52423ec0d44c58f68e83b614bfcd99dded66f
      with:
        go-version-file: ${{ inputs.go-mod }}
        cache-dependency-path: "**/go.sum"
        go-version: ${{ inputs.go-version }}
