name: 'init-go'
description: 'Check out the repo and setup-go'
inputs:
  go-mod:
    description: 'Go mod file'
    required: false
  go-version:
    description: 'Go versions to use'
    required: false
runs:
  using: "composite"
  steps:
    - name: Checkout repo
      uses: actions/checkout@09d2acae674a48949e3602304ab46fd20ae0c42f
      with:
        fetch-depth: 0

    - name: Setup Go
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5
      with:
        go-version-file: ${{ inputs.go-mod }}
        cache-dependency-path: "**/go.sum"
        go-version: ${{ inputs.go-version }}
