name: 'init-go'
description: 'Check out the repo and setup-go'
inputs:
  go-mod:
    description: 'Go mod file'
    required: false
  go-version:
    description: 'Go versions to use'
    required: false
runs:
  using: "composite"
  steps:
    - name: Checkout repo
      uses: actions/checkout@8edcb1bdb4e267140fa742c62e395cd74f332709
      with:
        fetch-depth: 0

    - name: Setup Go
      uses: actions/setup-go@8e57b58e57be52ac95949151e2777ffda8501267
      with:
        go-version-file: ${{ inputs.go-mod }}
        cache-dependency-path: "**/go.sum"
        go-version: ${{ inputs.go-version }}
