name: 'sonar-scan'
description: 'Scan code with SonarSource'
inputs:
  organization:
    required: true
    description: "The organization as set up in SonarCloud"
  project-key:
    required: true
    description: "The project key as set up in SonarCloud"
  sources:
    required: false
    description: "Path to source files to be included"
    default: .
  exclusions:
    required: false
    description: "Path to source files to be excluded"
  tests:
    required: false
    description: "Path to test files to be included"
  test-exclusions:
    required: false
    description: "Path to test files to exclude"
  verbose:
    required: false
    description: "Whether to activate verbose logs"
    default: 'true'
  coverage-exclusions:
    required: false
    description: "Path to files to exclude from coverage analysis"
  coverage-report:
    required: false
    description: "Path to the coverage report"

runs:
  using: "composite"
  steps:
    - uses: step-security/harden-runner@6c3b1c91e8873ae0c705b0709f957c7a6a5eaf10
      with:
        disable-sudo: true
        egress-policy: block
        allowed-endpoints: >
          api.github.com:443
          github.com:443
          scanner.sonarcloud.io:443
          sonarcloud.io:443

    - uses: actions/checkout@8459bc0c7e3759cdf591f513d9f141a95fef0a8f
      with:
        fetch-depth: 0

    - uses: SonarSource/sonarcloud-github-action@6bbd64e0cb2194e04addb429d669a9ee873eeeef
      with:
        args: >
          -Dsonar.organization=${{ inputs.organization }}
          -Dsonar.projectKey=${{ inputs.project-key }}
          -Dsonar.sources=${{ inputs.sources }}
          -Dsonar.exclusions=${{ inputs.exclusions }}
          -Dsonar.tests=${{ inputs.tests }}
          -Dsonar.test.exclusions=${{ inputs.test-exclusions }}
          -Dsonar.verbose=${{ inputs.verbose }}
          -Dsonar.coverage.exclusions=${{ inputs.coverage-exclusions }}
          -Dsonar.go.coverage.reportPaths=${{ inputs.coverage-report }}
