name: 'sonar-scan'
description: 'Scan code with SonarSource'
inputs:
  configuration:
    description: "Path to the configuration file."
    required: true
  cover-file:
    description: 'The output file name to store the coverage results in (defaults to .github/coverage.out)'
    required: false
    default: .github/coverage.out
  go-mod:
    description: 'Go mod file'
    required: false
  version:
    description: 'Go versions to use'
    required: false

runs:
  using: "composite"
  steps:
    - name: Harden Runner
      uses: step-security/harden-runner@6d3c2fe731c8f225990c8018cb71c337c0d9dfcd
      with:
        disable-sudo: true
        egress-policy: block
        allowed-endpoints: >
          api.github.com:443
          ea6ne4j2sb.execute-api.eu-central-1.amazonaws.com:443
          github.com:443
          golang.org:443
          objects.githubusercontent.com:443
          proxy.golang.org:443
          scanner.sonarcloud.io:443
          sonarcloud.io:443
          storage.googleapis.com:443
          sum.golang.org:443

    - name: Checkout repo
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      with:
        fetch-depth: 0

    - name: Setup Go
      uses: actions/setup-go@4ab57d7ea2fd0c9948210b2e0784e280674e7144
      with:
        cache: false
        go-version-file: ${{ inputs.go-mod }}
        go-version: ${{ inputs.go-version }}

    - uses: SonarSource/sonarcloud-github-action@e44258b109568baa0df60ed515909fc6c72cba92
      with:
        args: >
          -Dproject.settings=${{ inputs.configuration }}
          -Dsonar.go.coverage.reportPaths=${{ inputs.coverage-file }}