name: 'sonar-scan'
description: 'Scan code with SonarSource'
inputs:
  configuration:
    description: "Path to the configuration file."
    required: true
  coverage-command:
    description: 'The command to use to run the tests (defaults to go test -v -race -covermode=atomic -coverpkg=./...)'
    required: false
    type: string
    default: go test -v -race -covermode=atomic -coverpkg=./...
  coverage-output-file:
    description: 'The output file name to store the coverage results in (defaults to coverage.out)'
    required: false
    type: string
    default: coverage.out
  coverage-scope:
   description: 'The location to run the command on (defaults to ./...)'
   required: false
   type: string
   default: ./...
  go-mod:
    description: 'Go mod file'
    required: false
  version:
    description: 'Go versions to use'
    required: false

runs:
  using: "composite"
  steps:
    - name: Harden Runner
      uses: step-security/harden-runner@d7cf128fba8343bb6666acf77451879c0530cac8
      with:
        disable-sudo: true
        egress-policy: block
        allowed-endpoints: >
          api.github.com:443
          ea6ne4j2sb.execute-api.eu-central-1.amazonaws.com:443
          github.com:443
          golang.org:443
          objects.githubusercontent.com:443
          proxy.golang.org:443
          scanner.sonarcloud.io:443
          sonarcloud.io:443
          storage.googleapis.com:443
          sum.golang.org:443

    - name: Checkout repo
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      with:
        fetch-depth: 0

    - name: Setup Go
      uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32
      with:
        cache: false
        go-version-file: ${{ inputs.go-mod }}
        go-version: ${{ inputs.go-version }}

    - name: Code Coverage
      shell: bash
      run: ${{ inputs.coverage-command }} -coverprofile=${{ inputs.coverage-output-file }} ${{ inputs.coverage-scope }}

    - uses: SonarSource/sonarcloud-github-action@b7cc8bf2004f4a9ef190137d8831630e9ae5d2e7
      with:
        args: >
          -Dproject.settings=${{ inputs.configuration }}
