name: 'sonar-scan'
description: 'Scan code with SonarSource'
inputs:
  configuration:
    required: true
    description: "Path to the configuration file."
  coverage-report:
    required: false
    description: "Path to the coverage report file."

runs:
  using: "composite"
  steps:
    - name: Harden Runner
      uses: step-security/harden-runner@9ff9d14760a73102d9fa2f47131624137f50ead8
      with:
        disable-sudo: true
        egress-policy: block
        allowed-endpoints: >
          api.github.com:443
          github.com:443
          scanner.sonarcloud.io:443
          sonarcloud.io:443

    - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
      with:
        fetch-depth: 0

    - uses: SonarSource/sonarcloud-github-action@3da91d8a6aff5e898114575b30c6dc1e4787a254
      with:
        args: >
          -Dproject.settings=${{ inputs.configuration }}
          -Dsonar.go.coverage.reportPaths=${{ inputs.coverage-report }}
