name: 'sonar-scan'
description: 'Scan code with SonarSource'
inputs:
  configuration:
    required: true
    description: "Path to the configuration file."

runs:
  using: "composite"
  steps:
    - name: Harden Runner
      uses: step-security/harden-runner@f4f3f445f343c08c93d7771433e8dee4267e05b9
      with:
        disable-sudo: true
        egress-policy: block
        allowed-endpoints: >
          api.github.com:443
          ea6ne4j2sb.execute-api.eu-central-1.amazonaws.com:443
          github.com:443
          golang.org:443
          objects.githubusercontent.com:443
          proxy.golang.org:443
          scanner.sonarcloud.io:443
          sonarcloud.io:443
          storage.googleapis.com:443
          sum.golang.org:443

    - name: Checkout repo
      uses: actions/checkout@b80ff79f1755d06ba70441c368a6fe801f5f3a62
      with:
        fetch-depth: 0

    - name: Setup Go
      uses: actions/setup-go@4ab57d7ea2fd0c9948210b2e0784e280674e7144
      with:
        cache: false
        go-version-file: ${{ inputs.go-mod }}
        go-version: ${{ inputs.go-version }}

    - name: Sonar Coverage
      shell: bash
      run: go test -v -race -covermode=atomic -coverpkg=./...-coverprofile=.github/coverage.out ./... &&

    - uses: SonarSource/sonarcloud-github-action@13d84ab51ea6fc29e22a1288ec28cc71fd2eb19e
      with:
        args: >
          -Dproject.settings=${{ inputs.configuration }}