name: 'govulncheck'
description: 'Scan for known vulnerabilities in Go dependencies.'
inputs:
  check-test:
    required: true
    description: "Whether to analyze test files"

runs:
  using: "composite"
  steps:
    - name: Harden Runner
      uses: step-security/harden-runner@9ff9d14760a73102d9fa2f47131624137f50ead8
      with:
        disable-sudo: true
        egress-policy: audit

    - name: Init go
      uses: bytemare/actions/init-go@9d34c2ecdaa6860cd53d058f47f338c07289812d
      with:
        version: ${{ inputs.version }}

    - name: Install govulncheck
      run: go install golang.org/x/vuln/cmd/govulncheck@latest

    - name: Run govulncheck
      run:
