name: 'codecov'
description: 'Upload a coverage report to Codecov'
inputs:
  coverage-report:
    required: true
    description: "Path to the coverage report"

runs:
  using: "composite"
  steps:
    - name: Harden Runner
      uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f
      with:
        disable-sudo: true
        egress-policy: block
        allowed-endpoints: >
          api.codecov.io:443
          api.github.com:443
          cli.codecov.io:443
          github.com:443
          storage.googleapis.com:443

    - uses: codecov/codecov-action@9b01a3419101d2fd03eaa10f7495f7d03c6adf95
      with:
        file: ${{ inputs.coverage-report }}
