name: 'codecov'
description: 'Upload a coverage report to Codecov'
inputs:
  coverage-report:
    required: true
    description: "Path to the coverage report"

runs:
  using: "composite"
  steps:
    - name: Harden Runner
      uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7
      with:
        disable-sudo: true
        egress-policy: block
        allowed-endpoints: >
          api.codecov.io:443
          api.github.com:443
          cli.codecov.io:443
          github.com:443
          storage.googleapis.com:443

    - uses: codecov/codecov-action@5c47607acb93fed5485fdbf7232e8a31425f672a
      with:
        file: ${{ inputs.coverage-report }}
