name: golangci-lint

on:
  workflow_call:
    inputs:
      config-path:
        required: false
        description: 'Path to the GolangCI-Lint configuration file'
        type: string
        default: .github/.golangci.yml
      scope:
        required: false
        description: 'Go mod file (defaults to ./go.mod)'
        type: string
        default: ./...
      go-mod:
        required: false
        description: 'Go mod file (defaults to ./go.mod)'
        type: string
        default: ./go.mod

jobs:
  GolangCI-Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@6c3b1c91e8873ae0c705b0709f957c7a6a5eaf10
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            objects.githubusercontent.com:443
            raw.githubusercontent.com:443

      - uses: bytemare/actions/init-go@main
        with:
          go-mod: ${{ inputs.go-mod }}

      - uses: golangci/golangci-lint-action@692c9c9dba385536b59da68da5aef1775a6f94ea
        with:
          version: latest
          args: --config=${{ inputs.config-path }} ${{ inputs.scope }}
