name: Code Scanning

on:
  workflow_call:
    inputs:
      cover-command:
        description: 'The command to use to run the tests (defaults to go test -v -vet=all ./...)'
        required: false
        type: string
        default: go test -v -race -covermode=atomic -coverpkg=./...
      sonar-configuration:
        required: true
        description: "Path to the configuration file"
        type: string
    secrets:
      github:
        required: true
      sonar:
        required: true
      codecov:
        required: true
      semgrep:
        required: true

jobs:
  Cover:
    uses: ./.github/workflows/coverage-go.yml
    with:
      command: ${{ inputs.cover-command }}

  Semgrep:
    uses: ./.github/workflows/semgrep.yml
    with:
      token: ${{ secrets.semgrep }}

  Codecov:
    runs-on: ubuntu-latest
    needs: Cover
    steps:
      - name: Download code coverage report
        uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e
        with:
          name: ${{ needs.Cover.outputs.coverage-output-artefact }}

      - uses: bytemare/actions/codecov@main
        env:
          CODECOV_TOKEN: ${{ secrets.codecov }}
        with:
          coverage-report: ${{ needs.Cover.outputs.coverage-output-file }}
          
  Sonar:
    runs-on: ubuntu-latest
    needs: Cover
    steps:
      - name: Download code coverage report
        uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e
        with:
          name: ${{ needs.Cover.outputs.coverage-output-artefact }}

      - uses: bytemare/actions/sonar-scan@main
        env:
          GITHUB_TOKEN: ${{ secrets.github }}
          SONAR_TOKEN: ${{ secrets.sonar }}
        with:
          configuration: ${{ inputs.sonar-configuration }}