name: Semgrep
on:
  workflow_call:
    secrets:
      token:
        required: true

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.token }}
    container:
      image: semgrep/semgrep
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: step-security/harden-runner@9ff9d14760a73102d9fa2f47131624137f50ead8
        with:
          disable-sudo: false
          egress-policy: audit
          allowed-endpoints: >
            github.com:443

      - name: Checkout repo
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b

      - run: semgrep ci