name: Codecov

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  Codecov:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8a09271fed8277ab7fb02dbb5917c8d0e78323b4
        with:
          egress-policy: audit
          allowed-endpoints: >
          # init-go
            github.com:443
            golang.org:443
            keybase.io:443
            objects.githubusercontent.com:443
            proxy.golang.org:443
            storage.googleapis.com:443
            sum.golang.org:443
          # codecov
            api.codecov.io:443
            cli.codecov.io:443
            ingest.codecov.io:443
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./codecov-action
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
