name: Codecov

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  Codecov:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: ./codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
