name: Test Go

on:
  workflow_call:
    inputs:
      command:
        description: 'The command to use to run the tests (defaults to go test -v -vet=all ./...)'
        required: false
        type: string
        default: go test -v -vet=all ./...
      version:
        description: 'The Go version to use'
        required: false
        type: string

permissions: {}

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Init go
        uses: bytemare/actions/init-go@4166ee8110554c18c03ad257a3191ee9901f2bd6
        with:
          version: ${{ inputs.version }}

      - name: Run Tests
        run: ${{ inputs.command }}
