name: Sonar Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  SonarQube:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2
        with:
          fetch-depth: 0
      - uses: ./sonar-scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          configuration: ${{ inputs.sonar-configuration }}
          coverage-output-file: ${{ inputs.coverage-output-file }}
          go-mod: ${{ inputs.go-mod }}
