name: Scorecard analysis workflow
on:
  push:
    # Only the default branch is supported.
    branches:
      - main
  schedule:
    # Weekly on Saturdays.
    - cron: '30 1 * * 6'
  pull_request:
    # All branches are supported.
    branches: [ main ]

permissions: {}

jobs:
  analysis:
    uses: ./.github/workflows/scorecard.yml
    secrets:
      token: ${{ secrets.SCORECARD_TOKEN }}