name: Scorecard Analysis Workflow

on:
  schedule:
    # Weekly on Saturdays.
    - cron: '30 1 * * 6'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Declare default permissions as read-only.
permissions: read-all

jobs:
  Analysis:
    permissions:
      # Needed for Code scanning upload
      security-events: write
      # Needed for GitHub OIDC token if publish_results is true
      id-token: write
    uses: ./.github/workflows/scorecard.yml
    secrets:
      token: ${{ secrets.SCORECARD_TOKEN }}